In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# main data type is ndarray -  n dimensional array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a3 = np.array([ [[1,2,3],[4,5,6],[7,8,9]], [ [10,11,12], [13,14,15], [16,17,18]] ])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
# attributes
a1.shape

(3,)

In [9]:
a2.shape

(3, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 9, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Numpy Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
type(ones)

numpy.ndarray

In [31]:
zeros = np.zeros((2,3))

In [32]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
range_array = np.arange(1,5,2)

In [36]:
range_array

array([1, 3])

In [37]:
r_array = np.arange(1,8)

In [38]:
r_array

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
random_array = np.random.randint(0, 10,size = (2,3))

In [56]:
random_array

array([[2, 9, 0],
       [8, 4, 7]], dtype=int32)

In [57]:
r = np.random.random((5,3))

In [58]:
r

array([[0.50172798, 0.20264068, 0.15266977],
       [0.92911454, 0.62402789, 0.22403866],
       [0.16771589, 0.53670349, 0.46921827],
       [0.9926609 , 0.58758398, 0.37820183],
       [0.75171252, 0.57279937, 0.99920399]])

In [51]:
np.random.random((5,3))

array([[0.33255596, 0.82194223, 0.89226191],
       [0.69505839, 0.27354024, 0.88180909],
       [0.09301349, 0.5365318 , 0.60476056],
       [0.87650272, 0.44539719, 0.37437376],
       [0.07848775, 0.03504924, 0.64814284]])

In [52]:
np.random.rand(5,3)

array([[0.34644964, 0.55922114, 0.31664366],
       [0.90253538, 0.70209593, 0.02755863],
       [0.61328188, 0.29080248, 0.06349491],
       [0.91908304, 0.6283182 , 0.07482141],
       [0.27258832, 0.69856947, 0.17338128]])

In [54]:
np.random.rand(5,3)

array([[0.95492409, 0.39567867, 0.67689223],
       [0.37811327, 0.5299158 , 0.77017473],
       [0.43504433, 0.99069719, 0.0653448 ],
       [0.30930206, 0.19791329, 0.62300621],
       [0.33677588, 0.44080514, 0.85039374]])

In [59]:
np.random.randint(0, 10,size = (2,3))

array([[8, 3, 4],
       [7, 5, 3]], dtype=int32)

In [61]:
np.random.seed(0)
y = np.random.randint(0, 10,size = (2,3))

In [62]:
y

array([[5, 0, 3],
       [3, 7, 9]], dtype=int32)

In [63]:
np.random.randint(0, 10,size = (2,3))

array([[3, 5, 2],
       [4, 7, 6]], dtype=int32)

In [64]:
y

array([[5, 0, 3],
       [3, 7, 9]], dtype=int32)

In [65]:
#Seed() - pseudo random no.s 
#the random values ddoes not chnage when genereated again

In [69]:
np.random.randint(10)

6

In [72]:
d = pd.DataFrame(np.random.randint(10, size = (2,3)))
d

   0  1  2
0  5  0  2
1  3  8  1

In [75]:
np.random.seed(0)
d = pd.DataFrame(np.random.randint(10, size = (2,3)))
d

   0  1  2
0  5  0  3
1  3  7  9

In [76]:
d

   0  1  2
0  5  0  3
1  3  7  9

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a1

array([1, 2, 3])

In [80]:
a1[0]

np.int64(1)

In [82]:
a2[0]

array([1, 2, 3])

In [83]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [85]:
a3[ :2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [86]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [87]:
#Unique No. in random array
d

   0  1  2
0  5  0  3
1  3  7  9

In [88]:
d.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [89]:
y

array([[5, 0, 3],
       [3, 7, 9]], dtype=int32)

In [91]:
arr = np.unique(y)

In [92]:
arr

array([0, 3, 5, 7, 9], dtype=int32)

In [93]:
a4 = np.random.randint(10, size = (2,3,4,5))

In [94]:
a4

array([[[[3, 5, 2, 4, 7],
         [6, 8, 8, 1, 6],
         [7, 7, 8, 1, 5],
         [9, 8, 9, 4, 3]],

        [[0, 3, 5, 0, 2],
         [3, 8, 1, 3, 3],
         [3, 7, 0, 1, 9],
         [9, 0, 4, 7, 3]],

        [[2, 7, 2, 0, 0],
         [4, 5, 5, 6, 8],
         [4, 1, 4, 9, 8],
         [1, 1, 7, 9, 9]]],


       [[[3, 6, 7, 2, 0],
         [3, 5, 9, 4, 4],
         [6, 4, 4, 3, 4],
         [4, 8, 4, 3, 7]],

        [[5, 5, 0, 1, 5],
         [9, 3, 0, 5, 0],
         [1, 2, 4, 2, 0],
         [3, 2, 0, 7, 5]],

        [[9, 0, 2, 7, 2],
         [9, 2, 3, 3, 2],
         [3, 4, 1, 2, 9],
         [1, 4, 6, 8, 2]]]], dtype=int32)

In [95]:
a4.shape

(2, 3, 4, 5)

In [96]:
a4[:, :, :, :4]

array([[[[3, 5, 2, 4],
         [6, 8, 8, 1],
         [7, 7, 8, 1],
         [9, 8, 9, 4]],

        [[0, 3, 5, 0],
         [3, 8, 1, 3],
         [3, 7, 0, 1],
         [9, 0, 4, 7]],

        [[2, 7, 2, 0],
         [4, 5, 5, 6],
         [4, 1, 4, 9],
         [1, 1, 7, 9]]],


       [[[3, 6, 7, 2],
         [3, 5, 9, 4],
         [6, 4, 4, 3],
         [4, 8, 4, 3]],

        [[5, 5, 0, 1],
         [9, 3, 0, 5],
         [1, 2, 4, 2],
         [3, 2, 0, 7]],

        [[9, 0, 2, 7],
         [9, 2, 3, 3],
         [3, 4, 1, 2],
         [1, 4, 6, 8]]]], dtype=int32)